services:
  - type: web
    name: entreprise-transport
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:////app/etransport.db
