"""add_montant_contrat_to_cautions

Revision ID: 6033e58b2797
Revises: 84bbadcd9e22
Create Date: 2026-08-21 00:56:56.025490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6033e58b2797'
down_revision: Union[str, Sequence[str], None] = '84bbadcd9e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cautions', sa.Column('montant_contrat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cautions', 'montant_contrat')
    # ### end Alembic commands ###
