"""auto_sync_models_with_db

Revision ID: 84bbadcd9e22
Revises: 20260820_0002
Create Date: 2026-08-20 22:45:00.177605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bbadcd9e22'
down_revision: Union[str, Sequence[str], None] = '20260820_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_toggles',
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('enabled_for_gestionnaire', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_toggles_categorie'), 'feature_toggles', ['categorie'], unique=False)
    op.create_index(op.f('ix_feature_toggles_feature_name'), 'feature_toggles', ['feature_name'], unique=True)
    op.create_index(op.f('ix_feature_toggles_id'), 'feature_toggles', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('singleton_id', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('typography', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('company_rc', sa.String(length=100), nullable=True),
    sa.Column('company_nif', sa.String(length=100), nullable=True),
    sa.Column('company_nis', sa.String(length=100), nullable=True),
    sa.Column('company_ai', sa.String(length=100), nullable=True),
    sa.Column('company_phone', sa.String(length=100), nullable=True),
    sa.Column('company_logo_base64', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_singleton_id'), 'system_settings', ['singleton_id'], unique=True)
    op.create_table('crm_notes',
    sa.Column('partenaire_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notes_id'), 'crm_notes', ['id'], unique=False)
    op.create_table('depenses_vehicules',
    sa.Column('vehicule_id', sa.UUID(), nullable=False),
    sa.Column('categorie', sa.Enum('CARBURANT', 'PEAGE', 'PNEU', 'ASSURANCE', 'ENTRETIEN', 'REPARATION', 'PERSONNEL', 'AMORTISSEMENT', 'AUTRE', name='categoriedepensevehicule'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('kilometrage', sa.Float(), nullable=True),
    sa.Column('fournisseur', sa.String(length=150), nullable=True),
    sa.Column('justificatif', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_vehicules_id'), 'depenses_vehicules', ['id'], unique=False)
    op.create_table('factures',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('mois_realisation', sa.String(length=20), nullable=False),
    sa.Column('montant_facture', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PAYEE', 'EN_RETARD', 'ANNULEE', name='statutfacture'), nullable=False),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('mode_reglement', sa.Enum('ESPECE', 'VIREMENT', 'CHEQUE', 'CARTE', name='modepaiement'), nullable=True),
    sa.Column('date_reglement', sa.Date(), nullable=True),
    sa.Column('url_document_reglement', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['partenaires.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_numero'), 'factures', ['numero'], unique=True)
    op.create_table('receptions',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fournisseur_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('mode_reglement', sa.Enum('ESPECES', 'CHEQUE', 'VIREMENT', 'CREDIT', 'CCP', name='mode_reglement_reception'), nullable=False),
    sa.Column('motif', sa.String(length=200), nullable=True),
    sa.Column('reference_document', sa.String(length=100), nullable=True),
    sa.Column('url_pdf', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['partenaires.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptions_id'), 'receptions', ['id'], unique=False)
    op.create_index(op.f('ix_receptions_numero'), 'receptions', ['numero'], unique=True)
    op.create_table('reception_lignes',
    sa.Column('reception_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('montant_ligne', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reception_id'], ['receptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reception_lignes_id'), 'reception_lignes', ['id'], unique=False)
    op.create_index(op.f('ix_avenants_id'), 'avenants', ['id'], unique=False)
    op.add_column('cautions', sa.Column('date_echeance', sa.Date(), nullable=True))
    op.add_column('cautions', sa.Column('banque_emetteur', sa.String(length=150), nullable=True))
    op.add_column('cautions', sa.Column('lieu_demande', sa.String(length=200), nullable=True))
    op.add_column('cautions', sa.Column('lieu_soumission', sa.String(length=200), nullable=True))
    op.add_column('cautions', sa.Column('numero_compte_bancaire', sa.String(length=100), nullable=True))
    op.add_column('cautions', sa.Column('societe_nom', sa.String(length=200), nullable=True))
    op.add_column('cautions', sa.Column('client_societe_nom', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('cautions_numero_key'), 'cautions', type_='unique')
    op.create_index(op.f('ix_cautions_id'), 'cautions', ['id'], unique=False)
    op.create_index(op.f('ix_cautions_numero'), 'cautions', ['numero'], unique=True)
    op.create_index(op.f('ix_constats_id'), 'constats', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.drop_constraint(op.f('contrats_reference_key'), 'contrats', type_='unique')
    op.create_index(op.f('ix_contrats_id'), 'contrats', ['id'], unique=False)
    op.create_index(op.f('ix_contrats_reference'), 'contrats', ['reference'], unique=True)
    op.add_column('documents', sa.Column('document_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('idx_documents_entity'), table_name='documents')
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.drop_constraint(op.f('employes_matricule_key'), 'employes', type_='unique')
    op.drop_index(op.f('idx_employes_matricule'), table_name='employes')
    op.drop_index(op.f('idx_employes_type'), table_name='employes')
    op.create_index(op.f('ix_employes_id'), 'employes', ['id'], unique=False)
    op.create_index(op.f('ix_employes_matricule'), 'employes', ['matricule'], unique=True)
    op.create_index(op.f('ix_employes_type_employe'), 'employes', ['type_employe'], unique=False)
    op.add_column('interventions', sa.Column('cout_total', sa.Float(), nullable=False))
    op.drop_index(op.f('idx_interventions_num'), table_name='interventions')
    op.drop_constraint(op.f('interventions_numero_key'), 'interventions', type_='unique')
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_numero'), 'interventions', ['numero'], unique=True)
    op.add_column('mouvements_stock', sa.Column('reception_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_mouvements_stock_id'), 'mouvements_stock', ['id'], unique=False)
    op.create_foreign_key(None, 'mouvements_stock', 'receptions', ['reception_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_partenaires_nom'), table_name='partenaires')
    op.drop_index(op.f('idx_partenaires_role'), table_name='partenaires')
    op.create_index(op.f('ix_partenaires_id'), 'partenaires', ['id'], unique=False)
    op.create_index(op.f('ix_partenaires_nom_commercial'), 'partenaires', ['nom_commercial'], unique=False)
    op.create_index(op.f('ix_partenaires_role_partenaire'), 'partenaires', ['role_partenaire'], unique=False)
    op.drop_constraint(op.f('permis_numero_key'), 'permis', type_='unique')
    op.create_index(op.f('ix_permis_id'), 'permis', ['id'], unique=False)
    op.create_index(op.f('ix_permis_numero'), 'permis', ['numero'], unique=True)
    op.drop_index(op.f('idx_pieces_categorie'), table_name='pieces')
    op.drop_index(op.f('idx_pieces_ref'), table_name='pieces')
    op.drop_constraint(op.f('pieces_reference_key'), 'pieces', type_='unique')
    op.create_index(op.f('ix_pieces_categorie'), 'pieces', ['categorie'], unique=False)
    op.create_index(op.f('ix_pieces_id'), 'pieces', ['id'], unique=False)
    op.create_index(op.f('ix_pieces_reference'), 'pieces', ['reference'], unique=True)
    op.drop_index(op.f('idx_vehicules_immat'), table_name='vehicules')
    op.drop_constraint(op.f('vehicules_immatriculation_key'), 'vehicules', type_='unique')
    op.create_index(op.f('ix_vehicules_id'), 'vehicules', ['id'], unique=False)
    op.create_index(op.f('ix_vehicules_immatriculation'), 'vehicules', ['immatriculation'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicules_immatriculation'), table_name='vehicules')
    op.drop_index(op.f('ix_vehicules_id'), table_name='vehicules')
    op.create_unique_constraint(op.f('vehicules_immatriculation_key'), 'vehicules', ['immatriculation'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_vehicules_immat'), 'vehicules', ['immatriculation'], unique=False)
    op.drop_index(op.f('ix_pieces_reference'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_id'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_categorie'), table_name='pieces')
    op.create_unique_constraint(op.f('pieces_reference_key'), 'pieces', ['reference'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pieces_ref'), 'pieces', ['reference'], unique=False)
    op.create_index(op.f('idx_pieces_categorie'), 'pieces', ['categorie'], unique=False)
    op.drop_index(op.f('ix_permis_numero'), table_name='permis')
    op.drop_index(op.f('ix_permis_id'), table_name='permis')
    op.create_unique_constraint(op.f('permis_numero_key'), 'permis', ['numero'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_partenaires_role_partenaire'), table_name='partenaires')
    op.drop_index(op.f('ix_partenaires_nom_commercial'), table_name='partenaires')
    op.drop_index(op.f('ix_partenaires_id'), table_name='partenaires')
    op.create_index(op.f('idx_partenaires_role'), 'partenaires', ['role_partenaire'], unique=False)
    op.create_index(op.f('idx_partenaires_nom'), 'partenaires', ['nom_commercial'], unique=False)
    op.drop_constraint(None, 'mouvements_stock', type_='foreignkey')
    op.drop_index(op.f('ix_mouvements_stock_id'), table_name='mouvements_stock')
    op.drop_column('mouvements_stock', 'reception_id')
    op.drop_index(op.f('ix_interventions_numero'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.create_unique_constraint(op.f('interventions_numero_key'), 'interventions', ['numero'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_interventions_num'), 'interventions', ['numero'], unique=False)
    op.drop_column('interventions', 'cout_total')
    op.drop_index(op.f('ix_employes_type_employe'), table_name='employes')
    op.drop_index(op.f('ix_employes_matricule'), table_name='employes')
    op.drop_index(op.f('ix_employes_id'), table_name='employes')
    op.create_index(op.f('idx_employes_type'), 'employes', ['type_employe'], unique=False)
    op.create_index(op.f('idx_employes_matricule'), 'employes', ['matricule'], unique=False)
    op.create_unique_constraint(op.f('employes_matricule_key'), 'employes', ['matricule'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.create_index(op.f('idx_documents_entity'), 'documents', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'document_type')
    op.drop_index(op.f('ix_contrats_reference'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_id'), table_name='contrats')
    op.create_unique_constraint(op.f('contrats_reference_key'), 'contrats', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_constats_id'), table_name='constats')
    op.drop_index(op.f('ix_cautions_numero'), table_name='cautions')
    op.drop_index(op.f('ix_cautions_id'), table_name='cautions')
    op.create_unique_constraint(op.f('cautions_numero_key'), 'cautions', ['numero'], postgresql_nulls_not_distinct=False)
    op.drop_column('cautions', 'client_societe_nom')
    op.drop_column('cautions', 'societe_nom')
    op.drop_column('cautions', 'numero_compte_bancaire')
    op.drop_column('cautions', 'lieu_soumission')
    op.drop_column('cautions', 'lieu_demande')
    op.drop_column('cautions', 'banque_emetteur')
    op.drop_column('cautions', 'date_echeance')
    op.drop_index(op.f('ix_avenants_id'), table_name='avenants')
    op.drop_index(op.f('ix_reception_lignes_id'), table_name='reception_lignes')
    op.drop_table('reception_lignes')
    op.drop_index(op.f('ix_receptions_numero'), table_name='receptions')
    op.drop_index(op.f('ix_receptions_id'), table_name='receptions')
    op.drop_table('receptions')
    op.drop_index(op.f('ix_factures_numero'), table_name='factures')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_depenses_vehicules_id'), table_name='depenses_vehicules')
    op.drop_table('depenses_vehicules')
    op.drop_index(op.f('ix_crm_notes_id'), table_name='crm_notes')
    op.drop_table('crm_notes')
    op.drop_index(op.f('ix_system_settings_singleton_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_feature_toggles_id'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_feature_name'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_categorie'), table_name='feature_toggles')
    op.drop_table('feature_toggles')
    # ### end Alembic commands ###
