"""add_prix_unitaire_moyen_to_pieces

Revision ID: 9db1637ba2ef
Revises: 6033e58b2797
Create Date: 2026-08-26 23:54:10.664718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db1637ba2ef'
down_revision: Union[str, Sequence[str], None] = '6033e58b2797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention_pieces', sa.Column('prix_unitaire_applique', sa.Float(), nullable=False))
    op.add_column('interventions', sa.Column('cout_main_doeuvre', sa.Float(), nullable=False))
    op.add_column('interventions', sa.Column('cout_pieces', sa.Float(), nullable=False))
    op.add_column('pieces', sa.Column('prix_unitaire_moyen', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pieces', 'prix_unitaire_moyen')
    op.drop_column('interventions', 'cout_pieces')
    op.drop_column('interventions', 'cout_main_doeuvre')
    op.drop_column('intervention_pieces', 'prix_unitaire_applique')
    # ### end Alembic commands ###
