"""add_annee_realisation_to_facture

Revision ID: 15e54e2b2d12
Revises: 9db1637ba2ef
Create Date: 2026-08-29 18:55:18.989151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e54e2b2d12'
down_revision: Union[str, Sequence[str], None] = '9db1637ba2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('annee_realisation', sa.Integer(), server_default='2026', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'annee_realisation')
    # ### end Alembic commands ###
